apiVersion: apps/v1
kind: Deployment
metadata:
  name: breaking
  labels:
    app: breaking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: breaking
  template:
    metadata:
      labels:
        app: breaking
    spec:
      containers:
        - name: breaking
          image: fakhertalahmeh/breaking-1.7:latest
          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "500Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: breaking
  labels:
    app: breaking
spec:
  type: LoadBalancer
  selector:
    app: breaking
  ports:
    - protocol: TCP
      port: 8601
      targetPort: 8000